more

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -8,9 +8,12 @@ jobs:
   echo1:
     runs-on: ubuntu-latest
     steps:
+      - name: Sleep for 5 seconds
+        run: sleep 5
       - name: Failing step   
-        run: exit 1
-      - name: I will be skipped  
+        run: exit 1       # when a step fails, the job will skip all following steps by default, unless those steps have an `if`    
+                          # whose condition evaluates to true even after a failure.
+      - name: I will be skipped
         if: ${{ success() }}
         run: echo "I will print if previous steps succeeded"
       - name: I will execute  
